version: "3.7"

services:
  ## --------------------------- SUPLENTE AVATAR --------------------------- ##
  suplente-avatar:
    image: node:18-alpine
    working_dir: /app
    networks:
      - traefik_public
      - general_network
    environment:
      - NEXT_PUBLIC_SIMLI_API_KEY=${NEXT_PUBLIC_SIMLI_API_KEY}
      - NEXT_PUBLIC_VAPI_API_KEY=${NEXT_PUBLIC_VAPI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: >
      sh -c "apk add --no-cache git &&
         git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/faustosip/suplente-avatar.git /tmp/app &&
         cd /tmp/app &&
         npm install --legacy-peer-deps &&
         npm run dev -- -H 0.0.0.0"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.suplente-avatar.rule=Host(`natalia.agentcrmai.com`)
        - traefik.http.services.suplente-avatar.loadbalancer.server.port=3000
        - traefik.http.routers.suplente-avatar.service=suplente-avatar
        - traefik.http.routers.suplente-avatar.entrypoints=websecure
        - traefik.http.routers.suplente-avatar.tls.certresolver=le

networks:
  traefik_public:
    external: true
  general_network:
    external: true
