version: "3.7"
services:
## --------------------------- VAPI SIMLI DRIVE THRU --------------------------- ##
  vapi-simli-drive-thru:
    image: faustosip/vapi-simli-drive-thru:latest ## Tu imagen en Docker Hub
    networks:
     - faustoparedesnet ## Tu red interna existente
    environment:
     ## App Configuration
     - NODE_ENV=production
     - PORT=3000
     - HOSTNAME=0.0.0.0
      ## VAPI Configuration  
     - NEXT_PUBLIC_VAPI_PUBLIC_KEY=${VAPI_PUBLIC_KEY}
     - NEXT_PUBLIC_VAPI_ASSISTANT_ID=${VAPI_ASSISTANT_ID}
     ## Simli Configuration
     - NEXT_PUBLIC_SIMLI_API_KEY=${SIMLI_API_KEY}
     - NEXT_PUBLIC_SIMLI_FACE_ID=${SIMLI_FACE_ID}
     ## App Branding
     - NEXT_PUBLIC_APP_NAME=Doctor Donut Drive-Thru
     - NEXT_PUBLIC_APP_VERSION=1.0.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.vapi-drive-thru.rule=Host(`sophia.faustoparedesia.com`) ## Tu dominio correcto
        - traefik.http.services.vapi-drive-thru.loadBalancer.server.port=3000
        - traefik.http.routers.vapi-drive-thru.service=vapi-drive-thru
        - traefik.http.routers.vapi-drive-thru.entrypoints=websecure
        - traefik.http.routers.vapi-drive-thru.tls.certresolver=letsencryptresolver
## --------------------------- VAPI SIMLI DRIVE THRU --------------------------- ##

networks:
  faustoparedesnet: ## Tu red interna existente
    external: true
    name: faustoparedesnet
